name: Release shareservice Package

# on:
#   release:
#     types: [created]

on:
  push:
  pull_request:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      PROJECT_PREFIX: share-service
    steps:
      - name: Export Global Var
        run: |
          echo "PROJECT_HOME=$PWD" >> $GITHUB_ENV
          echo "TAG=`echo \`date +%Y%m%d\`.${GITHUB_SHA} | cut -c1-16`" >> $GITHUB_ENV

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: ossrh
          server-username: ${{ secrets.OSSRH_USER }}
          server-password: ${{ secrets.OSSRH_PASSWORD }}
          gpg-passphrase:  ${{ secrets.GPG_PASSWORD }}

      - name: Publish to Maven Central Repo
        uses: samuelmeuli/action-maven-publish@v1.4.0
        with:
          directory: $PROJECT_PREFIX
          maven_profiles: deploy #代码 pom 中的 profile 会引入发布需要的插件
          gpg_private_key: ${{ secrets.GPG_SECRET }}
          gpg_passphrase: ${{ secrets.GPG_PASSWORD }}
          nexus_username: ${{ secrets.OSSRH_USER }}
          nexus_password: ${{ secrets.OSSRH_PASSWORD }}
